# This is a basic workflow to help you get started with Actions

name: SplitPlace-Benchmarks

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ workflow ]
    paths:
      - 'workflow/workload/DockerImages/images/**'
      - '.github/workflows/*.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/workflow'
    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the MNIST_layer image
          run: docker build -t shreshthtuli/mnist_layer workflow/workload/DockerImages/images/MNIST_layer/
        - name: Push the MNIST_layer image
          run: docker push shreshthtuli/mnist_layer

